#include <string>
#include <iostream>

#include "cxxopts.hpp"

int launch(int argc, char** argv)
{
    cxxopts::Options options("cornerstone2", "proto to ue++ converter");
    options.add_options()
            ("src_path", "A path, where *.proto source files resides.", cxxopts::value<std::string>())
            ("dst_path", "A path, where generated C++ classes should be placed.", cxxopts::value<std::string>())
            ("wrappers_path", "Name of the folder, where files generated by protoc should reside.", cxxopts::value<std::string>())
            ("company_name", "Company name will be used to declare category, where RPC methods will reside.",cxxopts::value<std::string>())
            ("precompiled_header", "(Optional) Provide a valid relative or absolute path to the precompiled header.", cxxopts::value<std::string>());

    cxxopts::ParseResult cliOpts = options.parse(argc, argv);

    if (!cliOpts.count("src_path") ||
        !cliOpts.count("dst_path") ||
        !cliOpts.count("company_name") ||
        !cliOpts.count("wrappers_path"))
    {
        std::cout << options.help() << std::endl;
    }

    return 0;
}


int main(int argc, char** argv)
{
    return launch(argc, argv);
}
